# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  final_config = debug
endif
ifeq ($(config),release)
  final_config = release
endif

PROJECTS := final

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

final:
ifneq (,$(final_config))
	@echo "==== Building final ($(final_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(final_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   final"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"